name: Deploy to k3s on AWS

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Ensures files are available

    - name: Install SSH Key
      run: |
        echo "${{ secrets.AWS_EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Copy Kubernetes Manifest to AWS EC2
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem hello-world.yaml ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/ec2-user/

    - name: Deploy Nginx Application on AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        kubectl apply -f /home/ec2-user/hello-world.yaml
        kubectl rollout status deployment/hello-world
      
        EOF
